name: Phorest assignment
on: 
  push:
    branches:
      - main
  schedule: 
    - cron: '0 17 * * 1-5'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true